### ISSUE TITLE
Bug: Update Profile button on Profile page should be hit on enter key 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#117]
Update Profile button on Profile page should be primary

**Comment by kshitijbhardwaj** [comment]
It is primary Blue color. Are u seeing in white?

**Comment by theheapdump** [comment]
@bevanamit - i do not understand what is primary ??

**Comment by bevanamit** [comment]
@kshitijbhardwaj knows what i meant by saying primary, my understanding is a little wrong but kks got it. @anmoldeep0123

**Comment by bevanamit** [comment]
Not fixed

**Comment by kshitijbhardwaj** [comment]
This is not possible as happening in login and register. same thing which i have done in login and register i implemented here also. But since there are other components here like Date picker and all. the dom structure of the form is getting broken.
So to save this you have to click or tab to the update button and press enter.
Hence closing the issue.
